app/profile/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo


class ChangePassForm(FlaskForm):
    old_pass = PasswordField("Старый пароль: ", validators=[DataRequired()])
    password = PasswordField("Новый пароль",
                             validators=[DataRequired(),
                                         Length(min=4, max=50),
                                         EqualTo('confirm',
                                                 message='Пароли должны '
                                                         'совпадать')])
    confirm = PasswordField('Повторите новый пароль')
    submit = SubmitField("Изменить пароль")


class DeleteAccountForm(FlaskForm):
    pass_for_dell = PasswordField("Введите пароль",
                                  validators=[DataRequired(),
                                              EqualTo('confirm_for_dell',
                                                      message='Пароли должны '
                                                              'совпадать')])
    confirm_for_dell = PasswordField('Повторите пароль')
    submit = SubmitField("УДАЛИТЬ АККАУНТ")

app/profile/blueprint_profile.py
from flask import Blueprint, flash, render_template, redirect, url_for, request
from flask_jwt_extended import jwt_required, get_jwt_identity
from passlib.hash import bcrypt

from app.utils import Database
from app.client.model import Client
from app.profile.forms import ChangePassForm, DeleteAccountForm
from app.vote.utils import get_votes_count


profile_bp = Blueprint('profile', __name__)


@profile_bp.route("/", methods=['GET', 'POST'])
@jwt_required()
def profile():
    """Личный кабинет клиента."""
    context = dict()
    context['title'] = 'Личный кабинет'
    try:
        current_client = get_jwt_identity()

        context['stared_count'] = get_votes_count(client_id=current_client,
                                                  status='started')
        context['waiting_count'] = get_votes_count(client_id=current_client,
                                                   status='waiting')
        context['finished_count'] = get_votes_count(client_id=current_client,
                                                    status='finished')

    except Exception as e:
        flash(f'Error: <{e}>')

    return render_template("profile/profile.html", context=context)


@profile_bp.route("/settings", methods=['GET', 'POST'])
@jwt_required()
def settings():
    """Настройки личного кабинета клиента."""
    context = dict()
    context['title'] = 'Настройки'
    try:
        client = Client.query.get(get_jwt_identity())
        context['client'] = client
        context['token_api'] = request.args.get('token_api')

        if request.method == "POST":
            if "get_token_api" in request.form:
                token = client.get_token_api()
                return redirect(url_for('profile.settings', token_api=token))

    except Exception as e:
        flash(f'Error: <{e}>')

    return render_template("profile/settings.html", context=context)


@profile_bp.route("/change_pass", methods=['GET', 'POST'])
@jwt_required()
def change_pass():
    """Изменение пароля клиента."""
    form = ChangePassForm()
    context = dict()
    context['title'] = 'Смена пароля'
    try:
        if form.validate_on_submit():
            client = Client.query.get(get_jwt_identity())
            if not bcrypt.verify(form.old_pass.data, client.password):
                raise Exception('Неверный старый пароль')

            Database.up(table=Client, update_id=client.id,
                        data_update={'password': form.password.data})

            flash('Пароль успешно изменен')

            return redirect(url_for('profile.settings'))

    except Exception as e:
        flash(f'Error: <{e}>')

    return render_template("profile/change_pass.html", context=context,
                           form=form)


@profile_bp.route("/delete_account", methods=['GET', 'POST'])
@jwt_required()
def delete_account():
    """Удаление аккаунта."""
    form = DeleteAccountForm()
    context = dict()
    context['title'] = 'Удаление аккаунта'
    try:
        if form.validate_on_submit():
            client = Client.query.get(get_jwt_identity())

            if not bcrypt.verify(form.pass_for_dell.data, client.password):
                raise Exception('Неверный пароль')

            Database.dell(table=Client, delete_id=client.id)

            return redirect(url_for('client.logout'))

    except Exception as e:
        flash(f'Error: <{e}>')

    return render_template("profile/delete_account.html", context=context,
                           form=form)

app/templates/profile/change_pass.html
{% extends "profile/profile_base.html" %}

{% block profile_content %}

<h1 class="h1__form">Смена пароля</h1>
    <div class="form__register__block">

        <form class="form__change__pass" action="" method="post">

            {{ form.csrf_token() }}

            {% for field in form if field.name != "csrf_token" %}

                {% if field.name != "submit" %}
                    {{ field.label }}
                {% else %}
                    </br>
                    </br>
                {% endif %}

                <p>{{ field }}
                {% for error in field.errors %}
                    <span class="form__error__label">{{ error }}</span>
                {% endfor %}
                </p>
            {% endfor %}
        </form>
    </div>

{% endblock %}

app/templates/profile/delete_account.html
{% extends "profile/profile_base.html" %}

{% block profile_content %}

<h1 class="h1__form">Удаление аккаунта</h1>
    <h2 class="h2__profile">ВНИМАНИЕ!</h2>
    <p class="profile__settings__p">После нажатия кнопки "УДАЛИТЬ АККАУНТ" Ваш аккаунт будет удален безвозвратно и все данные связанные тоже.</p>
    <p class="profile__settings__p">Если Вы все равно хотите удалить свой аккаунт, то для его удаления введите свой пароль два раза.</p>

    <div class="form__delete__account">

        <form class="form__delete__account" action="" method="post">

            {{ form.csrf_token() }}

            {% for field in form if field.name != "csrf_token" %}

                {% if field.name != "submit" %}
                    {{ field.label }}
                {% else %}
                    </br>
                    </br>
                {% endif %}

                <p>{{ field }}
                {% for error in field.errors %}
                    <span class="form__error__label">{{ error }}</span>
                {% endfor %}
                </p>
            {% endfor %}
        </form>
    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends "profile/profile_base.html" %}

{% block profile_content %}

    <h2 class="h2__profile">Опросы:</h2>

    <h3 class="h3__profile">Запущенные опросы: {{ context.stared_count }}</h3>

    <h3 class="h3__profile">Ожидающие запуска опросы: {{ context.waiting_count }}</h3>

    <h3 class="h3__profile">Завершенные опросы: {{ context.finished_count }}</h3>

{% endblock %}

app/templates/profile/profile_base.html
{% extends "base.html" %}

{% block content %}

    <h1 class="h1__profile">Личный кабинет</h1>

    <div class="profile__menu">
        <ul class="profile__menu__list">
            <li class="profile__menu__item"><a href="{{ url_for('vote.votes') }}" class="profile__menu__link">Ваши опросы</a></li>
            <li class="profile__menu__item"><a href="{{ url_for('profile.settings') }}" class="profile__menu__link">Настройки</a></li>
        </ul>
    </div>

    <div class="profile__block">
        <div class="profile__flash__message__error">
            {% for msg in get_flashed_messages() %}
                <span>{{ msg }}</span>
            {% endfor %}
        </div>
        <div class="profile__content">
            {% block profile_content %}
            {% endblock %}
        </div>
    </div>

{% endblock %}

app/templates/profile/settings.html
{% extends "profile/profile_base.html" %}

{% block profile_content %}

    <div class="profile__settings__main_inf" >
        <h2 class="h2__profile">Информация аккаунта:</h2>
        <p class="profile__settings__p">Дата создания: {{ context.client.create.replace(microsecond=0) }}</p>
        <p class="profile__settings__p">Логин: {{ context.client.login }}</p>
        <p class="profile__settings__p">Email: {{ context.client.email }}</p>
        <p class="profile__settings__p"> <a href="{{ url_for('profile.change_pass') }}">сменить пароль</a></p>
        <br>
        <p class="profile__settings__p"> <a href="{{ url_for('profile.delete_account') }}">Удалить аккаунт</a></p>
    </div>

    <div class="profile__settings__token" >
        <h2 class="h2__profile">Токен для API</h2>
        <p class="profile__settings__p">Срок действия токена 3 дня.</p>
        <textarea name="Text1" cols="110" rows="6" readonly>
             {{ context.token_api }}
        </textarea>
        </br>
        <form class="form__get__token__api" action="" method="post">
            <button class="button__get__token_api" name="get_token_api" value="">Получить новый ТОКЕН</button>
        </form>
    </div>

{% endblock %}